### ISSUE TITLE
Reddit user having problems installing Jewbmx repo/zip file

### ISSUE THREAD

**Issue by ghost** [jewbmx/jewbmx.github.io#1]
Link to the thread: 
https://www.reddit.com/r/Addons4Kodi/comments/fclbfg/cant_install_jewbmx_something_wrong_with_the_url/

**Comment by phill-nz** [comment]
try http://lazykodi.com   dont load anything to do with tvaddons .. they are now a defacto virus

**Comment by RickFromTexas** [comment]
No thanks, I want nothing to do with kodi bae or TVA!
________________________________

**Comment by phill-nz** [comment]
yehh thats what i said .. lazy kodi has his repo .. my advice was to avoid it .. im pretty sure lazy kodi has nothing to do with tvaddons other than hosting its repo .. along with many many others .. its like a selected replacement for the old super repo

**Comment by jewbmx** [comment]
I see nothing wrong with my repo or url to install it lol, most likely a user error/glitch.

**Comment by phill-nz** [comment]
works for me as well ..
