### ISSUE TITLE
KCleaner in your Repo won't update on Kodi 18.9, needs Python 3.

### ISSUE THREAD

**Issue by justmygithub123** [jewbmx/jewbmx.github.io#10]
Hi, thank you for your on the great add-on Scrubs v2, but I have KCleaner installed on my Kodi 18.9 using the "Lanik Repo" which is for **_non_** Python 3 stuff so it does not try to install version 4.02, 
"Lanik (Python 3) Repo", is for Kodi 19 add-ons. Is there any way you can stop KCleaner in your Repo trying to update on Kodi 18? 
Thank you again, no hurry for a fix.

**Comment by jewbmx** [comment]
Ahh i honestly didnt even ponder that lol. I just kinda assumed the addon xml file was coded in that style, but i will go ahead and get that done for ya altho i wont be able to test it since i dont use anything under kodi v19

**Comment by justmygithub123** [comment]
No problem, I'll wait for the update and let you know if it works, no hurry. Thanks.

**Comment by jewbmx** [comment]
Looks like the file already has what i was thinking so im not sure how it can be done now lol, might just have to fidget with your settings to try and block my repo from doing it. Or maybe someone else will know whats needed and speak up.

**Comment by justmygithub123** [comment]
Ok don't worry about it, I'll just remove KCleaner, just happy Scrubs v2 is being updated. All the best to you.

**Comment by jewbmx** [comment]
Dont know if your version has the setting but i click the addons browser shortcut then pop open the settings from there and there is a setting under unknown sources that makes the repo update issue go away with your sorta problem.  I believe you could also just disable the addon or repo and have that issue go away too till ya enable it again to use it. (I like this option for some various shit that gets annoying lol.)
Theres one other addon.xml line of code i recall that might solve the issue too but im not quite sure if it will help or if it will be problematic lmao but ill toss it in anyways and find out 😀

**Comment by jewbmx** [comment]
Might need to wait a couple minutes then do some cleaning or trickery to make the repo and/or the old update reset to not show any kcleaner update from my repo or whatnot lol that way you can see if this new update i posted fixes your issue or not.

**Comment by justmygithub123** [comment]
Yep just tried that disabled and cleared Cleared all cache, but 4.02aa showed up, was 4.02a. I don't want to waist your time with such a minor issue, but thank you for trying, By the way did you know about running Kodi in Portable mode, I'll guess you do.

https://kodi.wiki/view/Portable_mode

**Comment by jewbmx** [comment]
Im gonna go ahead and remove the kcleaner addon from the repo then add it into the github source url/repo for installing the repos in kodi. That way its completely optional and out the way because it isnt mine anyways and i dont plan to keep updating unless something else miraculously causes a error/issue lol.

**Comment by justmygithub123** [comment]
I just seen that when I checked for updates it was gone. Cheers. Even the Lanik repo has two repos one for python 2 and one for python 3. Best to keep thinks simple, like me, lol.

All the best.

**Comment by jewbmx** [comment]
Yea when ya goto use my github.io as a source for a zip install you now see my repo, lanik py2, lanik py3, and kcleaner. Works well and is organized how my brain wants it too lol. Kinda surprised that i didnt think of doing it sooner or at the start.
