### ISSUE TITLE
Scrubs v2 5.1.13.

### ISSUE THREAD

**Issue by Greg0580** [jewbmx/jewbmx.github.io#11]
Hello. 
I have a few questions.  I am using kodi 20. On a 4k Max Firestick. 

Why I like this addon. Can I ask why you don't have a search button for movies and one for TV Shows.  Like if I want to do a search for Captian Marvel I can't and the same if I try do a search for a tv show for Fbi.  There's only a Search tool for both with a list of TMDB on both.

And your TMDB helper player url is not working  when you go to TMDB Helper Options/Select player then Scrubs v2 and then play with Scrubs v2 press on it the cogwheel circles and the Scrapers box's flashes up for about a second and disappears and Nothing happens.  
Thank you for  your time much appreciated.

**Comment by phill-nz** [comment]
i am using scrubs / tv shows / search tools / tv shows (TMBD)  / new search ...  as we type 
it works well

**Comment by phill-nz** [comment]
try a different skin confluence or one of the eon series and you may get something easier for your device and you to use

**Comment by Greg0580** [comment]
I don't use skins. And don't use builds.  Thank you for your reply.  I was only trying to make suggestions.  And did mean to offend you.
And my Firestick Max has plenty of storage space About 3 GBs.



Sent from my Galaxy



-------- Original message --------
From: phill-nz ***@***.***>
Date: 22/02/23 21:10 (GMT+12:00)
To: "jewbmx/jewbmx.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jewbmx/jewbmx.github.io] Scrubs v2 5.1.13. (Issue #11)


try a different skin confluence or one of the eon series and you may get something easier for your device and you to use

**Comment by phill-nz** [comment]
no offense taken .. just trying to help 
 skins change a lot of things with kodi .. they are not just paint jobs 

i agree with you on builds 




 
 

I don't use skins. And don't use builds. Thank you for your reply. I was only trying to make suggestions. And did mean to offend you.
And my Firestick Max has plenty of storage space About 3 GBs.



Sent from my Galaxy



-------- Original message --------
From: phill-nz ***@***.***>
Date: 22/02/23 21:10 (GMT+12:00)
To: "jewbmx/jewbmx.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jewbmx/jewbmx.github.io] Scrubs v2 5.1.13. (Issue #11)


try a different skin confluence or one of the eon series and you may get something easier for your device and you to use

**Comment by Greg0580** [comment]
You are correct  my apologies.  Just use to seeing  Search  and not  Search Tools
Thank you my bad 👎.
I like this addon.  Slowly learning more about it and like your Scrapers and links i use Filepursuit. As well as real debird.
Have a Good day. 👍



Sent from my Galaxy



-------- Original message --------
From: phill-nz ***@***.***>
Date: 22/02/23 21:08 (GMT+12:00)
To: "jewbmx/jewbmx.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jewbmx/jewbmx.github.io] Scrubs v2 5.1.13. (Issue #11)


i am using scrubs / tv shows / search tools / tv shows (TMBD) / new search ... as we type
it works well

**Comment by Greg0580** [comment]
OK Allgood  no problem. 👍



Sent from my Galaxy



-------- Original message --------
From: phill-nz ***@***.***>
Date: 22/02/23 22:02 (GMT+12:00)
To: "jewbmx/jewbmx.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jewbmx/jewbmx.github.io] Scrubs v2 5.1.13. (Issue #11)


just to clarify .. i am not jewbmx

i have just been using his adon for must be close to a decade
he is often busy so if the answer is known a lot of others will answer it before he gets time to






You are correct my apologies. Just use to seeing Search and not Search Tools
Thank you my bad 👎.
I like this addon. Slowly learning more about it and like your Scrapers and links i use Filepursuit. As well as real debird.
Have a Good day. 👍



Sent from my Galaxy



-------- Original message --------
From: phill-nz ***@***.***>
Date: 22/02/23 21:08 (GMT+12:00)
To: "jewbmx/jewbmx.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jewbmx/jewbmx.github.io] Scrubs v2 5.1.13. (Issue #11)


i am using scrubs / tv shows / search tools / tv shows (TMBD) / new search ... as we type
it works well

**Comment by jewbmx** [comment]
Thanks for being a mod while i sleep phill lol.
Personally i dont see any issue or question to respond to lol since the search works fine or seems to for me.
And as for that player bullshit its not my responsibility thats for the dev that made your extended info mod fork 😉 meaning whoever made your tmdb helper needs to be a helper for that problem lol.
