### ISSUE TITLE
json iptv

### ISSUE THREAD

**Issue by crak3rjack** [jewbmx/jewbmx.github.io#14]
@jewbmx Hi i added this link in the "mixed.py" but it won't play,  it needs the "user-agent" in order to work... my question is there any way you could get it to work and thanks.
link does work tested in android!
    {"title": "A&E", "url": "{http}s2.smartersapp{dot}net:80/play/XphQ_uI_Xhxxig7Y7wgHqMrsa4wWUC3s1UFxJH-iaf8|User-Agent=SyS1stemAp0", "image": ""},

**Comment by jewbmx** [comment]
@crak3rjack i just updated the addon to 1.0.09
you should now be able to add your own custom channels/links
or create your own lists using a example template i uploaded to its own repo ;)

i personally dont click on random links given to me by people so this should solve your problems while leaving me out the mix lol.
also as a side note, you should try not to post real links without breaking them like i did to your post ;)

**Comment by crak3rjack** [comment]
@jewbmx Really appreciate taking a look at it and quick fix, I'll take for a test drive and super thanks bud!💪

**Comment by jewbmx** [comment]
If ya need any info for the new stuff i left pretty much everything people would need inside the information section/file.
Also tested everything i added before the update and im happy with it lol
