### ISSUE TITLE
Suggestion to play through seasons

### ISSUE THREAD

**Issue by Deadlineem** [jewbmx/jewbmx.github.io#16]
Autoplay feature is working great, wondering if theres a way to make this play through each season.  Like if i started S1 of a tv show, just let it play through into season 2, 3, so on.

To expand, maybe make this feature toggleable for those who dont want it to do that.

**Comment by jewbmx** [comment]
Pretty sure no addon or module does a auto play function that goes from season to season lol, they all likely end their process at the end of the selected season and have you manually select the next season.

While i haven't tested this trick/tweak you could check this setup out and see if it will help out your streaming tho lol https://troypoint.com/auto-play-in-kodi/
I think everything in its steps are able to be done with scrubs but it probably wont be exactly what you want, altho maybe flattening the seasons could work.
I dont personally use any of them settings or features tho so i cant say if any of it works lmao
