### ISSUE TITLE
Enabling Dev Mode

### ISSUE THREAD

**Issue by ALEXK4747** [jewbmx/jewbmx.github.io#17]
Hello Jewbmx i am Alex you say in your settings in the Devish section to contact you if we want to enable the Dev Mode,How do we do this?
Thank You!

**Comment by jewbmx** [comment]
Firstly it doesn't say anything like that anywhere lmao, secondly there is no dev mode just a dev menu which is a lazy space for me, also means im not about to do a walk thru or explanation of anything related to it lol.

**Comment by ALEXK4747** [comment]
thank you i enabled it already all good
