### ISSUE TITLE
Scraper for this site

### ISSUE THREAD

**Issue by Deadlineem** [jewbmx/jewbmx.github.io#19]
https://fmovies.to/tv/family-guy-j20r8/1-1

Each episode is like 1-1, 1-2, 1-3, so on and so forth.  Seems simple enough to add into scrubs and i noticed some of the family guy episodes dont play right, they show up but dont play due to the sources or the scrapers, not sure which one causes it.

**Comment by jewbmx** [comment]
pretty sure that site and/or its code has never been figured out and put into a working scraper lol which is sorta sad since its a common find.
