### ISSUE TITLE
Scrubs Does Not Remember Kodi Viewtype

### ISSUE THREAD

**Issue by MadMax4Q2** [jewbmx/jewbmx.github.io#20]
Scrubs does not remember viewtype within Kodi e.g. using Aeon Nox SiLVO skin and set viewtype within scubs v2 for a list to Info Wall and when you go back to that list its changed back to Kodis default List View type. Needs View Type save option within addon settings.

**Comment by jewbmx** [comment]
Since the addon has been working fine for over 5 years with only fools or noobs complaining or having issues imma just assume you did something wrong and you can try google, blogs, or reddit 😉.  My help center closed down a month or so back due to budget cuts 🤭

**Comment by phill-nz** [comment]
scrubs / tools / setup view types / movies, tv shows, seasons, episodes, ( "enter" )/  switch left, select view type you want,  then " click here to save " 
it works 
signed 
" unpaid help center "
you are using the worst skin for ease of use .. try confluence

**Comment by MadMax4Q2** [comment]
> Since the addon has been working fine for over 5 years with only fools or noobs complaining or having issues imma just assume you did something wrong and you can try google, blogs, or reddit 😉. My help center closed down a month or so back due to budget cuts 🤭

Yep, I feel like both a noob and a fool for overlooking that feature within the tools area 🥴. 
Just wanted to say thanks jewbmx for this quality addon to Kodi and for keeping Scrubs alive all this time.



> scrubs / tools / setup view types / movies, tv shows, seasons, episodes, ( "enter" )/ switch left, select view type you want, then " click here to save " it works signed " unpaid help center " you are using the worst skin for ease of use .. try confluence

Thanks for pointing it out phill-nz 😅
