### ISSUE TITLE
Not showing any tv or movie links

### ISSUE THREAD

**Issue by Scoob71** [jewbmx/jewbmx.github.io#21]
Tv shows explore IMDb 
Genre
crime or any of them 
Come up with two dots doesn’t find any link
Tried reinstalling kodi and v2 but still come back 
To the same thing 🙏🤔

**Comment by phill-nz** [comment]
the problem is only on IMDb .. has been for days 
TMDb still works but has a different sort order 
good enough for a hopefully temp emergency .. i am not sure if jb has any control over that part of the code so he may not be able to do anything
