### ISSUE TITLE
scrubs v2 is not working

### ISSUE THREAD

**Issue by mrusli70** [jewbmx/jewbmx.github.io#25]
scrubs v2 is not working please fix it thank you.

**Comment by phill-nz** [comment]
it works .. lots of other things dont work well .. but .. scrubs v2 works and is still working ( tested 5 min ago ) .. thank you

**Comment by Deadlineem** [comment]
> it works .. lots of other things dont work well .. but .. scrubs v2 works and is still working ( tested 5 min ago ) .. thank you

its hit or miss for me, it works for a few months then stops.

**Comment by eeden003** [comment]
ScrubsV2 is NOT being updated/maintained by the owner. But ScrubsV2 still works ! However, the BEST site with series (BSTSRS) has movied a while ago so ScrubsV2 cannot access it anymore without an update ! BTW, there are less ans less sites withh FREE links on www !

**Comment by jewbmx** [comment]
Yall are wasting your time replying to foolish spam posts like this one lol. Your also in the wrong repo/place :) ya should be talkin in the regular "repo" repo issues where im discussing the current update lmao

**Comment by jewbmx** [comment]
Btw @eeden003 is your current bstsrs .in or .cc? If so then its gonna be available again when i push my update. Another classic type of scraper thats back again is projectfreetv lol

**Comment by Melann956** [comment]
Scrubs is working for me don't understand how it's not for others...

Melissa

________________________________

**Comment by eeden003** [comment]
Hello @jewbmx  .  The current site that I use is .in.  I like that site very much, it is fast and uptodate with new series and downloading with a PC is easy ánd a lot of links. Keep up the good work, I'm looking forward to your update(s). Thanks !

**Comment by eeden003** [comment]
Hello @jewbmx . Your update works gréat ! What a difference an update makes ! Links after links, more then 100 links and counting, and working, and all FREE WORKING links with great screen quality.  Thanks to yóu and all the people that helped/advised you. Keep up the good work !
