### ISSUE TITLE
Not compatible with Kodi 19

### ISSUE THREAD

**Issue by araujorm** [jewbmx/jewbmx.github.io#3]
Hi.

Most addons in the repo are not compatible with Kodi 19. Are there any hopes of them being ported to the new Kodi version?

Thanks in advance and best regards.

**Comment by jewbmx** [comment]
a update for kodi version 19 is slowly being done and eventually gonna be uploaded lol.
makin/made alot of changes, plus i dipped from codin for a while.

**Comment by Arthur1967** [comment]
Do you have a kodi 19 version yet￼

**Comment by jewbmx** [comment]
Technically yea but i am far from done with my current updating project.
Also im using kodi 19 only now so i dont plan to worry about older kodi versions working with my addons. Kinda like how ive decided to abandon alternative languages lol.

**Comment by Arthur1967** [comment]
So your add-on will work with Kodi 19.1￼ thank you for all the work￼

**Comment by phill-nz** [comment]
cheers jewbmx .. i thought you had dropped the project ..  please give notice when its ready so i can install ..

**Comment by jewbmx** [comment]
Looks like my wifi or app was a bit glitchy the other day when i replied to ya phill lol. But to resay it again :) ...
When i finally get done and goto upload the new version of scrubs i will most likely do a wipe and refresh to my repo so its clean and all upto date. Between that and the actual upload im sure word will spread like a wild fire as it seems to in the "kodiverse"
