### ISSUE TITLE
Not an issue, but a COMPLIMENT !

### ISSUE THREAD

**Issue by eeden003** [jewbmx/jewbmx.github.io#4]
Dear Sir(s) or Madam, my compliments for your update today. Your addon is now working great here on Kodi 18.9 and 19.4.
I can now find many many links/streams, even all of the Law & vOrder (Law and Order) series with verymany working links.
Other addons cannot find FREE links because of the & in the titles !
Other series have now 60-100 or even more streams, so....very good work.
Jan.

**Comment by phill-nz** [comment]
just installed and checked on 19.3 .. had to delete and clean all data from previous .. works as well as expected .. really dam well .. thanks ..  work well done .. phill

**Comment by jewbmx** [comment]
Thank you 3 for the feedback, feel free to complain if you find any problems/issues lol. (Third persons the one that hit like with a 👍)
And to resolve your comment a bit eeden003, i am the only person(guy) here not a group besides my mental roommates. Altho the credit to your title work along with alot of other code goes to host505.
And thanks phill for the versions info, im only on 19 so its good to know lol.
And i totally forgot to warn people that a fresh install is needed to prevent problems 🙃
