### ISSUE TITLE
I can only see 21 items/streams when using the episodes widgets, even when I have set it to 40 items/page, and there always is only one page.

### ISSUE THREAD

**Issue by eeden003** [jewbmx/jewbmx.github.io#8]
Hello there.
First, your addon finds much more working streams then The Promise and The Crew, thanks for that !
Secondly, I can only see 21 items/streams when using the episodes widgets, even when I have set it to 40 items/page, and there always is only one page.
Other addons have a calender and have much more then 21 items per day.
If you cannot repair this, well, your addon works fantastic and that is what matters more !
So, keep up the good work, thanks.

**Comment by jewbmx** [comment]
Closing this since we have covered it in emails already 😉
