### ISSUE TITLE
Jewbmx kodi issue 

### ISSUE THREAD

**Issue by SonyPiatkowo** [jewbmx/jewbmx.github.io#9]
Hi,
When I try to search TV shows return list is empty...
Kodi 19.3
Jewbmx 5.0.32

**Comment by jewbmx** [comment]
Doesnt give much info/details but i guess you can try to uninstall completely counting any related files then try to install again fresh and see if that fixes your problem

**Comment by SonyPiatkowo** [comment]
Hi,
I jav have installed kodi + jewbmx on a new device. Still, the same issue
appears.

Trying to do :
1. Open Scrubs v2
2. Go to TV shows
3. Search tools
4. TV shows (Tmbd)
5. New search
6. Typing : paw patrol

Got no results..

Actually, trying to browse TV shows doesn't give any output as well.

Cheers!


pt., 4 lis 2022, 09:07 użytkownik jewbmx ***@***.***> napisał:

**Comment by phill-nz** [comment]
works for me 
20+ episodes 2020 pups do something from 2019

**Comment by SonyPiatkowo** [comment]
Opened vpn from New Zealand.
Works good.

Seems to be location issue.

I'm surfing from Poland...

pt., 4 lis 2022, 09:45 użytkownik phill-nz ***@***.***>
napisał:

**Comment by SonyPiatkowo** [comment]
Seems to be my ISP router issue as on mobile data working fine...
